#!/bin/sh
export PATH=/usr/local/bin:$PATH

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR=$(git rev-parse --show-toplevel)

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | docker exec -i ukr_php bash -c "cd /var/www/vhost && vendor/bin/grumphp git:pre-commit --skip-success-output")
